AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/SymbolArray:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - cn
    - dn

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Layout/EndOfLine:
  Enabled: false
